### PR TITLE
Implement Responsive layout

### LINKED ISSUE #41: Use a responsive layout for portrait windows
While individual elements in the Playground are responsive, the layout is not. Consider this screenshot from an iPhone window emulation:

Screenshot from 2022-09-12 13-09-58

Since there are two main elements in the playground (editor on the left and output+tutorial on the right), I think the best solution would be to have these two elements span the full width horizontally and be on top of one another on mobile/portrait windows.

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
fixes #41 

Currently, I took the logo for rotate button from https://www.iconfinder.com/icons/326583/orientation_rotation_screen_icon.

**Output (Desktop):**
Screenshot 2023-02-01 at 8 07 10 PM

**Output (Desktop Portrait):**
Screenshot 2023-02-01 at 8 08 21 PM

**Output (Phone Portrait):**
Screenshot 2023-02-01 at 8 10 52 PM

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
This is ready. Please possibly review and share feedback.

**Comment by Jay9874** [comment]
Can I work on this project?
Im a cs undergraduate, currently in 2nd year. I have made projects on React and MERN, I can help in making frontend UX better.

**Comment by Shaikh-Ubaid** [comment]
Team, this is ready. Please share if any modifications/updates are needed. I had a great time working on this.

**Review by milancurcic — APPROVED** [review]
Sorry for the delay. Thanks a lot @Shaikh-Ubaid, I tested this, it works great. Will merge.

**Comment by Shaikh-Ubaid** [comment]
Thank you for the approval and merging!

**Pull request merged**
