### PR TITLE
Upgraded UI, Fixed minor bugs, Added Instructions for Production

### PR DESCRIPTION
**Pull request by ashirrwad**
* I have restructured the UI to ease understanding for users.
* The Tutorial now has a prompt and uses the main editor instead of code snippets.
* Added a fix for #23 
* Also added tweaks to pre build libraries as stated in #24 
* Fixed minor faults in the README and added instructions for production.

### CODE REVIEW

**Comment by ashirrwad** [comment]
@everythingfunctional @milancurcic please assist with review.

**Review by everythingfunctional — APPROVED** [review]
I think there are certainly some little things that could be improved, and we gave some suggestions in our call, but I'd be happy merging this as is and addressing anything else as separate PRs.

**Comment by everythingfunctional** [comment]
I will give a couple of hours for @milancurcic or @arjenmarkus to comment in case they think anything needs to be addressed as part of this PR, but then I'll merge it.

**Comment by ashirrwad** [comment]
I'll add the small tweaks like button positioning and text edits within 20 mins, things like Developer's guide can be pushed with another PR.

**Comment by everythingfunctional** [comment]
> I'll add the small tweaks like button positioning and text edits within 20 mins, things like Developer's guide can be pushed with another PR.

Just let me know when it's ready

**Review by milancurcic — APPROVED** [review]
Thank you, let's go ahead with it and we'll iterate on it in separate PRs.

**Comment by everythingfunctional** [comment]
:+1: I'm going to go ahead and merge. Let's focus on getting this deployed now. We can iterate on UI a little bit if we have time after that.

**Pull request merged**
