### PR TITLE
Add: Shortcut for 'run' ( Resolve #44)

### LINKED ISSUE #44: Shortcut for 'run'
Just tried the Playground and it's great but I found it a bit cumbersome to click the run button all the time. Could there be a short cut, e.g. Ctrl+Enter or something similar? If there already is one, maybe put a cheat sheet on the site.

### PR DESCRIPTION
**Pull request by henilp105**
This PR adds an Run code Shortcut ( Currently Control or Command  Key) to the Playground I would like to request the Fortran community to Add their Review , Suggestion, Discussion for this Feature. Please Feel Free to suggest New Combination for the Run shortcut.

Resolves:
- [x] #44 

Thanks and Regards,
Henil

CC @awvwgk @milancurcic @ashirrwad

### CODE REVIEW

**Comment by milancurcic** [comment]
Is it just Control/Command or Control/Command + something?

Ctrl+r or Ctrl+Enter seems reasonable.

**Comment by henilp105** [comment]
@milancurcic sir, currently it is only control, but can change to control + enter. (we won't be able to use the browser used combinations like ctrl r, ctrl s, as they have run priority).

**Comment by milancurcic** [comment]
OK, let's do Ctrl + Enter in absence of other ideas. We certainly can't let it be just Ctrl because that would trigger the submission of the code when the user tries to do Ctrl + Anything while on the page.

**Comment by henilp105** [comment]
Demo is LIVE at : https://playground-frontend-hrjz0pr1h-henilp105-gmailcom.vercel.app/

**Comment by henilp105** [comment]
@milancurcic sir, Demo is LIVE at : https://playground-frontend-hrjz0pr1h-henilp105-gmailcom.vercel.app

**Review by milancurcic — APPROVED** [review]
Thanks!

**Pull request merged**
