### PR TITLE
GitHub Action to deploy the frontend to gh-pages

### PR DESCRIPTION
**Pull request by milancurcic**
Only the frontend for now. I need to study some more how best to deploy/update the backend with an SSH key from GH Actions, so that will be a separate PR.

@awvwgk please check if everything looks as best practice for a Fortran-lang project.

This PR needs #35 to be merged first.

### CODE REVIEW

**Review by everythingfunctional — APPROVED** [review]
LGTM. I guess it means we're using GitHub Pages for hosting the forntend? I'll admit that I don't understand what the `build/.nojekyll` or `build/CNAME` files are for, but if this works I'm happy with it.

**Comment by milancurcic** [comment]
Yes, following Ashirwad's suggestion in [this comment](https://github.com/fortran-lang/playground/issues/25#issuecomment-1241793808).

`.nojekyll` tells GitHub to not attempt to use Jekyll to build the site. As I understand it, this only matters if we have files or directories that begin with an underscore, which Jekyll would exclude from the site. We don't have such files, but `.nojekyll` ensures that if they're ever pushed to the site in the future, they wouldn't be silently excluded.

`CNAME` tells GitHub to serve at the custom domain specified in that file.

**Comment by henilp105** [comment]
@milancurcic Sir, It seems that we would have to use `JamesIves/github-pages-deploy-action@v4.4.0`  this has an extra 'v' instead of `JamesIves/github-pages-deploy-action@4.4.0` I have tested this as the current version produces errors .

Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk

**Comment by milancurcic** [comment]
Thanks @henilp105, good catch, I fixed it.

**Comment by milancurcic** [comment]
I'll merge and if needed we can fix in follow-up PRs.

**Pull request merged**
