### PR TITLE
Initial support for responsive layout

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
towards #41 

This PR improves the following:
- Makes the Navbar responsive
- Fixes the overflow of tutorial start banner
- And other minor fixes/improvements

**Output (Desktop):**

image

**Output (Potrait):**

potrait-image

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
This is ready. Please possibly review and share feedback.

**Comment by milancurcic** [comment]
Thank you, @Shaikh-Ubaid! I'll review this.

Do you think that the mobile layout could be split in the horizontal direction instead of vertical, like I described in #41? We could do it in a separate PR, but wondering if you planned to tackle that as well or not.

**Comment by Shaikh-Ubaid** [comment]
>Do you think that the mobile layout could be split in the horizontal direction instead of vertical, like I described in https://github.com/fortran-lang/playground/issues/41? We could do it in a separate PR, but wondering if you planned to tackle that as well or not.

Yes, I am hoping to tackle it.

**Comment by ashirrwad** [comment]
Thank you for the PR,  It works good. Just a suggestion though, will it be better if we add some margin for the output/tutorial box? The buttons feel crammed to me, but this is something that needs more opinions on it. 
Everything else works fine. 
image
(I used 1rem margin-left for this)

**Review by ashirrwad — APPROVED** [review]
LGTM!

**Comment by Shaikh-Ubaid** [comment]
Thank you for the approval @ashirrwad !

**Review by milancurcic — APPROVED** [review]
Thanks @Shaikh-Ubaid and @ashirrwad!

**Comment by Shaikh-Ubaid** [comment]
Thank you for approval and merging @milancurcic .

**Pull request merged**
